export const myEvents = [3, 7, 12];

export const events = [
  {
    "id": 0,
    "name": "re:Invent",
    "startDate": "2023-11-28",
    "endDate": "2023-12-2",
    "location": "Las Vegas, USA",
    "url": "https://reinvent.awsevents.com/",
  },
  {
    "id": 1,
    "name": "DevOpsCon",
    "startDate": "2023-6-20",
    "endDate": "2023-6-23",
    "location": "Berlin, Germany",
    "url": "https://devopscon.io/berlin/",
  },
  {
    "id": 2,
    "name": "Mobile World Congress",
    "startDate": "2023-02-29",
    "endDate": "2023-03-2",
    "location": "Barcelona, Spain",
    "url": "https://www.mwcbarcelona.com/",
  },
  {
    "id": 3,
    "name": "Hannover Messe",
    "startDate": "2023-4-17",
    "endDate": "2023-4-21",
    "location": "Hannover, Germany",
    "url": "https://www.hannovermesse.de/de",
  },
  {
    "id": 4,
    "name": "Himss",
    "startDate": "2023-4-17",
    "endDate": "2023-4-21",
    "location": "Chicago, USA",
    "url": "https://www.himss.org/global-conference",
  },
  {
    "id": 5,
    "name": "AWS Madrid Summit",
    "startDate": "2023-5-4",
    "endDate": "2023-5-5",
    "location": "Madrid, Spain",
    "url": "https://aws.amazon.com/es/events/summits/madrid/",
  },
  {
    "id": 6,
    "name": "Prace Winter School",
    "startDate": "2023-12-7",
    "endDate": "2023-12-9",
    "location": "Online",
    "url": "https://events.prace-ri.eu/event/1215",
  },
  {
    "id": 7,
    "name": "re:Mars",
    "startDate": "2023-06-21",
    "endDate": "2023-06-24",
    "location": "Las Vegas, USA",
    "url": "https://remars.amazonevents.com/",
  },
  {
    "id": 8,
    "name": "re:Inforce",
    "startDate": "2023-6-26",
    "endDate": "2023-6-27",
    "location": "Boston, USA",
    "url": "https://reinforce.awsevents.com",
  },
  {
    "id": 9,
    "name": "ISC",
    "startDate": "2023-5-29",
    "endDate": "2023-6-2",
    "location": "Hamburg, Germany",
    "url": "https://www.isc-hpc.com",
  },
  {
    "id": 10,
    "name": "HashiConf Europe",
    "startDate": "2023-6-20",
    "endDate": "2023-6-22",
    "location": "Amsterdam, Netherlands",
    "url": "https://hashiconf.com/europe",
  },
  {
    "id": 11,
    "name": "KubeCon",
    "startDate": "2023-5-16",
    "endDate": "2023-5-20",
    "location": "Valencia, Spain",
    "url": "https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/",
  },
  {
    "id": 12,
    "name": "AWS AnalytiCon EMEA",
    "startDate": "2023-9-21",
    "endDate": "2023-9-22",
    "location": "Madrid, Spain",
    "url": "https://pages.awscloud.com/AnalytiCON-madrid-2023.html",
  },
  {
    "id": 13,
    "name": "AWS Summit AMER",
    "startDate": "2023-8-24",
    "endDate": "2023-8-26",
    "location": "Online, Virtual",
    "url": "https://aws.amazon.com/events/summits/online/americas",
  },
  {
    "id": 14,
    "name": "Container Days",
    "startDate": "2023-9-5",
    "endDate": "2023-9-7",
    "location": "Hamburg, Germany",
    "url": "https://www.containerdays.io",
  },
  {
    "id": 15,
    "name": "London TechWeek",
    "startDate": "2023-6-13",
    "endDate": "2023-6-17",
    "location": "London, UK",
    "url": "https://londontechweek.com/",
  },
  {
    "id": 16,
    "name": "Dublin TechSummit",
    "startDate": "2023-06-15",
    "endDate": "2023-05-16",
    "location": "Dublin, Ireland",
    "url": "https://dublintechsummit.tech",
  },
  {
    "id": 17,
    "name": "Dev-Ops/CloudNative",
    "startDate": "2023-05-25",
    "endDate": "2023-05-25",
    "location": "Boston, USA",
    "url": "https://www.techstrongevents.com/live-days-devops-cloud-native-boston",
  },
  {
    "id": 18,
    "name": "CyberSecurity Cloud Expo",
    "startDate": "2023-12-01",
    "endDate": "2023-12-02",
    "location": "London, UK",
    "url": "https://www.cybersecuritycloudexpo.com/global",
  },
  {
    "id": 19,
    "name": "Digital Enterprise Show",
    "startDate": "2023-6-14",
    "endDate": "2023-6-16",
    "location": "Malaga, Spain",
    "url": "https://www.des-show.com/",
  },
  {
    "id": 20,
    "name": "WWW Conference 123",
    "startDate": "2023-6-14",
    "endDate": "2023-6-16",
    "location": "Malaga, Spain",
    "url": "https://www.des-show.com/",
  },
]